version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: XARVIS_MONGO
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
    networks:
      - xarvis-network
    
#Docker Networks
networks:
  xarvis-network:
    driver: bridge

#Docker Volumes
volumes:
  dbdata:
    driver: local